---
kind: pipeline
name: default

steps:
  - name: Run rspec
    image: ruby:2.6
    commands:
      - gem install bundler:2.1.4
      - bundle install
      - bundle exec rspec

  - name: Release gems
    image: ruby:2.6
    environment:
      GEM_CREDENTIALS:
        from_secret: gem_credentials
    commands:
      - mkdir -p ~/.gem
      - echo $GEM_CREDENTIALS | base64 -d > ~/.gem/credentials
      - chmod 0600 ~/.gem/credentials
      - gem build kycaidplus.gemspec
      - gem push kycaidplus*.gem
    when:
      branch:
        - master

trigger:
  event:
    - push
